volumes:
  redis-cache:  # Volume para persistir o cache do Redis
  db-data:  # Volume para persistir os dados do banco de dados

services:
  drupal:
    build: ./  # Use o Dockerfile local
    container_name: drupal
    ports:
      - "8080:80"
    volumes:
          - ./web:/var/www/html
          - ./web/sites/default/config/sync:/var/www/html/sites/default/config/sync
          - ./web/sites/default/config/sync/config-site.tar.gz:/config-site.tar.gz  # Montando o arquivo de configuração
    environment:
      - DRUPAL_DB_HOST=db
      - DRUPAL_DB_NAME=drupal
      - DRUPAL_DB_USER=drupal
      - DRUPAL_DB_PASSWORD=drupal
    depends_on:
      - db
      - redis  # Adiciona dependência do Redis
    entrypoint: /usr/local/bin/entrypoint.sh  # Adiciona o script de inicialização

  db:
    image: mariadb:latest
    container_name: drupal_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - ./db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:6.2.7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-cache:/data:delegated
